<?php

namespace App\Console\Commands;

use App\Models\Region;
use Illuminate\Console\Command;
use DB;

class SeedCountries extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'seed:countries';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Seed countries into the database';

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
        // Davlatlar ro'yxati
        $countries = [
            'Afgʻoniston',
            'Albaniya',
            'Jazoir',
            'Andorra',
            'Angola',
            'Antigua va Barbuda',
            'Argentina',
            'Armaniston',
            'Avstraliya',
            'Avstriya',
            'Ozarbayjon',
            'Bagama orollari',
            'Bahrayn',
            'Bangladesh',
            'Barbados',
            'Belarus',
            'Belgiya',
            'Beliz',
            'Benin',
            'Butan',
            'Boliviya',
            'Bosniya va Gertsegovina',
            'Botsvana',
            'Braziliya',
            'Bruney',
            'Bolgariya',
            'Burkina-Faso',
            'Burundi',
            'Kabo-Verde',
            'Kambodja',
            'Kamerun',
            'Kanada',
            'Markaziy Afrika Respublikasi',
            'Chad',
            'Chili',
            'Xitoy',
            'Kolumbiya',
            'Komor orollari',
            'Kongo',
            'Kosta-Rika',
            'Xorvatiya',
            'Kuba',
            'Kipr',
            'Chexiya',
            'Daniya',
            'Jibuti',
            'Dominika',
            'Dominikan Respublikasi',
            'Sharqiy Timor',
            'Ekvador',
            'Misr',
            'Salvador',
            'Ekvatorial Gvineya',
            'Eritreya',
            'Estoniya',
            'Eswatini',
            'Efiopiya',
            'Fiji',
            'Finlyandiya',
            'Fransiya',
            'Gabon',
            'Gambiya',
            'Gruziya',
            'Germaniya',
            'Gana',
            'Gretsiya',
            'Grenada',
            'Gvatemala',
            'Gvineya',
            'Gvineya-Bisau',
            'Gayana',
            'Gaiti',
            'Gonduras',
            'Vengriya',
            'Islandiya',
            'Hindiston',
            'Indoneziya',
            'Eron',
            'Iroq',
            'Irlandiya',
            'Isroil',
            'Italiya',
            'Yamayka',
            'Yaponiya',
            'Iordaniya',
            'Qozogʻiston',
            'Keniya',
            'Kiribati',
            'Shimoliy Koreya',
            'Janubiy Koreya',
            'Quvayt',
            'Qirgʻiziston',
            'Laos',
            'Latviya',
            'Livan',
            'Lesoto',
            'Liberiya',
            'Liviya',
            'Lixtenshteyn',
            'Litva',
            'Lyuksemburg',
            'Madagaskar',
            'Malavi',
            'Malayziya',
            'Maldiv orollari',
            'Mali',
            'Malta',
            'Marshall orollari',
            'Mavritaniya',
            'Mavrikiy',
            'Meksika',
            'Mikroneziya',
            'Moldova',
            'Monako',
            'Mongoliya',
            'Chernogoriya',
            'Marokash',
            'Mozambik',
            'Myanma',
            'Namibiya',
            'Nauru',
            'Nepal',
            'Niderlandiya',
            'Yangi Zelandiya',
            'Nikaragua',
            'Niger',
            'Nigeriya',
            'Shimoliy Makedoniya',
            'Norvegiya',
            'Ummon',
            'Pokiston',
            'Palau',
            'Panama',
            'Papua - Yangi Gvineya',
            'Paragvay',
            'Peru',
            'Filippin',
            'Polsha',
            'Portugaliya',
            'Qatar',
            'Ruminiya',
            'Rossiya',
            'Ruanda',
            'Sent-Kits va Nevis',
            'Sent-Lyusiya',
            'Sent-Vinsent va Grenadin',
            'Samoa',
            'San-Marino',
            'San-Tome va Prinsipi',
            'Saudiya Arabistoni',
            'Senegal',
            'Serbiya',
            'Seyshell orollari',
            'Syerra-Leone',
            'Singapur',
            'Slovakiya',
            'Sloveniya',
            'Solomon orollari',
            'Somali',
            'Janubiy Afrika Respublikasi',
            'Janubiy Sudan',
            'Ispaniya',
            'Shri-Lanka',
            'Sudan',
            'Surinam',
            'Shvetsiya',
            'Shveytsariya',
            'Suriya',
            'Tayvan',
            'Tojikiston',
            'Tanzaniya',
            'Tailand',
            'Togo',
            'Tonga',
            'Trinidad va Tobago',
            'Tunis',
            'Turkiya',
            'Turkmaniston',
            'Tuvalu',
            'Uganda',
            'Ukraina',
            'Birlashgan Arab Amirliklari',
            'Birlashgan Qirollik',
            'AQSh',
            'Urugvay',
            'Oʻzbekiston',
            'Vanuatu',
            'Vatikan',
            'Venesuela',
            'Vetnam',
            'Yaman',
            'Zambiya',
            'Zimbabve'
        ];

        foreach ($countries as $country) {
            Region::insert(['name' => $country]);
        }

        $this->info('Countries seeded successfully!');
        return 0;
    }
}
